### PR TITLE
add error message to unknown error types

### PR DESCRIPTION
**Pull request by gowthamravichandran**
This fix helps in understanding the underlying issue with the input string better.

#22

### CODE REVIEW

**Review by gsdriver — COMMENTED** [review]
I like this idea of adding in a more detailed error message - I could see this being extended to other cases to provide more description (for example, for a break with an invalid duration a message of "time must be less than 10 seconds" would aid in debugging). Can you do 2 things to accommodate this:

1) Update README.md to note the new optional `message` field in the return object
2) Add a test case demonstrating this. You'll need to update `runTest` as well so it includes the message field if present, but this will be useful if we add this field in more error types going forward

**Comment by gowthamravichandran** [comment]
Totally agree, I am doing something like the following for [ssmllint.com](https://ssmllint.com)  (still a work in progress, do share your thoughts) Thanks to your library!

```
    function StringifyError(errorObj: any, text: string) {
        const lineNumber = getLineNumber(text, errorObj.position);
        if (errorObj.type === 'tag' && errorObj.attribute && errorObj.value) {
            return `The tag "${errorObj.tag}" with attribute "${errorObj.attribute}" has invalid value "${errorObj.value}" at line ${lineNumber} \n`;
        } else if (errorObj.type === 'tag' && errorObj.attribute) {
            return `The tag "${errorObj.tag}" has invalid attribute "${errorObj.attribute}" at line ${lineNumber}\n`;
        } else if (errorObj.type === 'tag') {
            return `Invalid tag "${errorObj.tag}" at line ${lineNumber}\n`;
        } else {
            return `Unknown error type: ${errorObj.type} at line ${lineNumber}\n`;
        }
    }
```
A crude form of handling, definitely could be improved.

Open to ideas/thoughts :)

**Comment by gsdriver** [comment]
> Totally agree, I am doing something like the following for [ssmllint.com](https://ssmllint.com) (still a work in progress, do share your thoughts) Thanks to your library!
> 
> ```
>     function StringifyError(errorObj: any, text: string) {
>         const lineNumber = getLineNumber(text, errorObj.position);
>         if (errorObj.type === 'tag' && errorObj.attribute && errorObj.value) {
>             return `The tag "${errorObj.tag}" with attribute "${errorObj.attribute}" has invalid value "${errorObj.value}" at line ${lineNumber} \n`;
>         } else if (errorObj.type === 'tag' && errorObj.attribute) {
>             return `The tag "${errorObj.tag}" has invalid attribute "${errorObj.attribute}" at line ${lineNumber}\n`;
>         } else if (errorObj.type === 'tag') {
>             return `Invalid tag "${errorObj.tag}" at line ${lineNumber}\n`;
>         } else {
>             return `Unknown error type: ${errorObj.type} at line ${lineNumber}\n`;
>         }
>     }
> ```
> 
> A crude form of handling, definitely could be improved.
> 
> Open to ideas/thoughts :)

Hmm .. I end up getting an error "Variant Also Negotiates" when I visit the site

**Review by gsdriver — APPROVED** [review]

**Comment by gowthamravichandran** [comment]
Sorry about that, still in development. was playing around with some DNS settings.

can you try now? test with some ssml strings.

[ssmllint.com](https://ssmllint.com)

Do share your thoughts! If you think we can move this discussion somewhere else more appropriate, let me know!

**Comment by gsdriver** [comment]
I like it - the formatting feature is pretty cool, and I appreciate the error / more detailed warning showing up at the bottom of the screen. While the formatting keeps the SSML tag structure in place, it removes the content within the tags - e.g. 

```
<speak>Hi<break time='1s'/></speak>
```

 becomes

```
<speak>
    <break time="1s"></break>
</speak>
```

**Comment by gowthamravichandran** [comment]
Good catch! the xml formatter keeps removing it. I need to fix that. 

Cheers!

**Pull request merged**
